[build-system]
requires = ["setuptools", "cython>=0.29", "wheel",
            "pathlib2; python_version < '3'",
            "repoze.lru; python_version < '3'",
           ]
build-backend = "setuptools.build_meta"

# [tool.coverage.run]
# plugins = ["Cython.Coverage"]